services:
  otel-collector:
    build: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]

  tempo:
    build: tempo
    command: ["-config.file=/etc/tempo-config.yml"]
    ports:
      - "3200:3200"

  loki:
    build: loki
    command: ["-config.file=/etc/loki/loki-config.yml"]
    ports:
      - "3100:3100"

  prometheus:
    build: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"

  grafana:
    build: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
      - otel-collector
