version: "3.9"

configs:
  otel_collector_config:
    file: ./etc/otel-collector/otel-collector-config.yml
  tempo_config:
    file: ./etc/tempo/tempo-config.yml
  loki_config:
    file: ./etc/loki/loki-config.yml
  prometheus_config:
    file: ./etc/prometheus/prometheus.yml
  grafana_ini:
    file: ./etc/grafana/grafana.ini

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    configs:
      - source: otel_collector_config
        target: /etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]

  tempo:
    image: grafana/tempo:latest
    configs:
      - source: tempo_config
        target: /etc/tempo-config.yml
    command: ["-config.file=/etc/tempo-config.yml"]
    ports:
      - "3200:3200"

  loki:
    image: grafana/loki:latest
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yml
    command: ["-config.file=/etc/loki/local-config.yml"]
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    configs:
      - source: grafana_ini
        target: /etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - tempo
      - prometheus
      - loki

