auth_enabled: false

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces      # ← new traces folder
    wal:
      path: /tmp/tempo/wal         # ← WAL stays here

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  ring:
    kvstore:
      store: memberlist
      prefix: collectors/
    heartbeat_period: 5s
    heartbeat_timeout: 1m
  processor:
    local_blocks: {}
    span_metrics: {}
    service_graphs: {}
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
  registry:
    collection_interval: 15s
    external_labels:
      source: tempo