auth_enabled: false

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
    wal:
      path: /tmp/tempo/wal

metrics_generator:
  # actually turn the generator on
  enabled: true

  # which time-series processors to run
  processor:
    # required for TraceQL metrics like rate(), count_over_time(), etc.
    local_blocks: {}

  # where the generator stores its own WAL of partial blocks
  storage:
    path: /tmp/tempo/generator/wal
    wal:

  # (optional) ship these blocks off to Prometheus via remote_write
  registry:
    collection_interval: 15s
    external_labels: {}
    remote_write: []

# if you have tenant-overrides enabled, make sure local_blocks is in your
# overrides.defaults.metrics_generator.processors list, e.g.:
overrides:
  defaults:
    metrics_generator:
      processors: 
      - service-graphs
      - span-metrics
      - local-blocks