name: Publish Compose OCI Artifact

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ otel-collector, tempo, loki, prometheus, grafana ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/spire-labs/${{ matrix.service }}:latest

  publish:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.35.1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Compose app (with Grafana)
        run: |
          docker compose build
          yes y |docker compose publish ghcr.io/${{ github.repository }}:latest \
            --resolve-image-digests \
            --with-env
      - name: Publish Compose app (no Grafana)
        run: |
          docker compose -f docker-compose.no-grafana.yml build
          yes y |docker compose -f docker-compose.no-grafana.yml publish ghcr.io/${{ github.repository }}:no-grafana \
            --resolve-image-digests \
            --with-env